/* Laboratório local: o iframe tem origem opaca e CSP sem rede. Nenhuma sessão,
   chave ou endpoint do produto é enviado ao primeiro acesso em avaliação. */
(function(){
'use strict';
var resumeOnMount=false;
var KEY='easyapp:gestao:testes-primeiro-acesso:v1', channel='', source=null, run=null, db={runs:[]}, saving=true;
var scenarios={manual:'Começar do zero',planilha:'Planilha organizada',duvidas:'Planilha com dúvidas',empresa:'Pessoal e empresa',falha:'Interrupção na importação'};
var instructions={manual:'Escolha começar do zero e cadastre uma conta que você reconheça.',planilha:'Escolha a planilha e confira os dados encontrados.',duvidas:'Escolha a planilha e resolva a dúvida entre previsão e gasto realizado.',empresa:'Escolha a planilha para conferir contas pessoais e da empresa.',falha:'Escolha a planilha. A primeira tentativa falha para testar a recuperação.'};
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function load(){try{db=JSON.parse(localStorage.getItem(KEY)||'{"runs":[]}');if(!db||!Array.isArray(db.runs))db={runs:[]};db.runs=db.runs.slice(-20);}catch(e){db={runs:[]};saving=false;}run=db.runs.find(function(x){return x.id===db.current;})||null;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));saving=true;}catch(e){saving=false;}status();}
function seconds(ms){var n=Math.round((ms||0)/1000);return Math.floor(n/60)+'min '+String(n%60).padStart(2,'0')+'s';}
function total(s){return Object.keys(s&&s.times||{}).reduce(function(n,k){return n+s.times[k];},0);}
function status(){var el=document.getElementById('labStatus');if(el)el.textContent=saving?'Progresso salvo somente neste navegador.':'Não foi possível salvar neste navegador. Exporte o relatório antes de sair.';var metrics=document.getElementById('labMetrics');if(metrics)metrics.innerHTML=run&&run.state?'<b>'+seconds(total(run.state))+'</b> em teste · '+(run.state.errors||0)+' validações · '+(run.state.complete?'Concluído':'Etapa '+(run.state.step+1)+' de 5'): 'Comece um cenário para medir o tempo.';var steps=document.getElementById('labSteps');if(steps)steps.innerHTML=run&&run.state?['Começar','Seu caminho','Conferir','Seu mês','Seu app'].map(function(n,i){return '<div style="display:flex;justify-content:space-between;padding:5px 0"><span>'+n+'</span><b>'+seconds(run.state.times[i]||0)+'</b></div>';}).join(''):'Os tempos aparecem quando você inicia uma rodada.';}
function html(){resumeOnMount=!!source;source=null;load();return '<style>.labGrid{display:grid;grid-template-columns:minmax(0,460px) minmax(240px,1fr);gap:24px;align-items:start;margin-top:20px}.labPreview{grid-row:span 2}.labFeedback{grid-column:2}.labPhone[hidden]{display:none!important}.labPhone{width:100%;height:800px;border:1px solid #40516c;border-radius:22px;background:#101726}.labTools{padding:18px;border:1px solid var(--line);border-radius:16px;background:var(--card)}.labTools label{display:block;margin:14px 0 6px;font-size:13px;color:var(--tx2)}.labTools select,.labTools textarea{width:100%;background:var(--bg);color:var(--tx);border:1px solid var(--line);border-radius:9px;padding:11px;font:inherit}.labTools button{min-height:44px;margin:8px 6px 0 0;background:#202d44;color:#eaf1fc;border:1px solid #40516c;border-radius:10px;padding:10px 13px;font:inherit;cursor:pointer}.labTools button:disabled{opacity:.5;cursor:default}#labNew{background:#377bed;border-color:#377bed}.labTools summary{cursor:pointer;padding:12px 0;font-weight:600}.labTools textarea{min-height:100px;resize:vertical}.labHistory{display:grid;gap:8px;margin-top:12px}.labHistory button{text-align:left;width:100%;background:var(--card);border:1px solid var(--line);padding:12px;border-radius:10px;color:var(--tx)}#labPaused{padding:25px;text-align:center;border:1px dashed var(--line);border-radius:20px;min-height:180px}#labHistory:empty:after{content:"Nenhuma rodada ainda.";color:var(--tx2)}@media(max-width:780px){.labGrid{grid-template-columns:1fr}.labTools{grid-row:1}.labPreview{grid-row:2}.labFeedback{grid-column:1;grid-row:3}.labPhone{height:740px;max-width:460px;display:block;margin:auto}}</style>'+
'<h2>Testar primeiro acesso</h2><p class="sub">Experimente a proposta de boas-vindas como um cliente novo, quantas vezes quiser. Use dados fictícios.</p><div class="sub">Fluxo em avaliação: importação e conexão bancária simuladas. O primeiro acesso dos clientes e a Pluggy permanecem como estão.</div><div class="labGrid"><div class="labPreview"><div id="labPaused">Escolha um cenário e toque em <b>Novo teste</b>.</div><iframe id="labFrame" class="labPhone" title="Primeiro acesso em avaliação" sandbox="allow-scripts" hidden></iframe></div><aside class="labTools"><h2 style="margin-top:0">Sua rodada de teste</h2><label for="labScenario">Cenário</label><select id="labScenario">'+Object.keys(scenarios).map(function(k){return '<option value="'+k+'"'+(run&&run.scenario===k?' selected':'')+'>'+scenarios[k]+'</option>';}).join('')+'</select><p id="labGuide" class="sub" style="margin-top:10px"></p><button id="labNew" class="bt">Novo teste</button><button id="labResume" class="bt">Continuar teste</button><button id="labPause" class="bt" hidden>Pausar</button><button id="labRestart" class="bt">Reiniciar do zero</button><p id="labStatus" class="sub" style="margin-top:12px" role="status"></p><div id="labMetrics" style="margin:14px 0"></div><details><summary>Tempo por etapa</summary><div id="labSteps" class="sub"></div></details></aside><section class="labTools labFeedback"><label for="labRating">Como foi a experiência?</label><select id="labRating"><option value="">Ainda não avaliei</option><option value="facil">Fácil, consegui sem ajuda</option><option value="duvidas">Consegui, mas tive dúvidas</option><option value="dificil">Difícil, precisei de ajuda</option><option value="desisti">Eu desistiria aqui</option></select><label for="labNotes">O que ficou fácil ou confuso?</label><textarea id="labNotes" maxlength="3000" placeholder="Ex.: não entendi se era para informar saldo ou limite."></textarea><button id="labExport" class="bt">Exportar relatório</button><details><summary>Rodadas anteriores</summary><p class="sub">Até 20 rodadas, guardadas neste navegador.</p><div id="labHistory" class="labHistory"></div></details></section></div>';}
function history(){var el=document.getElementById('labHistory');if(!el)return;el.innerHTML=db.runs.slice().reverse().map(function(r){return '<button data-lab-run="'+esc(r.id)+'"><b>'+esc(scenarios[r.scenario])+'</b><br><small>'+new Date(r.created).toLocaleString('pt-BR')+' · '+(r.state&&r.state.complete?'concluído':r.state?'etapa '+(r.state.step+1):'não iniciado')+' · '+seconds(total(r.state))+'</small></button>';}).join('');el.querySelectorAll('[data-lab-run]').forEach(function(b){b.onclick=function(){pause();run=db.runs.find(function(r){return r.id===b.dataset.labRun;});db.current=run.id;persist();details();start();};});}
function details(){if(!document.getElementById('labScenario'))return;if(run)document.getElementById('labScenario').value=run.scenario;document.getElementById('labRating').value=run&&run.rating||'';document.getElementById('labNotes').value=run&&run.notes||'';document.getElementById('labGuide').textContent=instructions[document.getElementById('labScenario').value];document.getElementById('labResume').disabled=!run;document.getElementById('labRestart').disabled=!run;document.getElementById('labRating').disabled=!run;document.getElementById('labNotes').disabled=!run;status();history();}
function pause(){var frame=document.getElementById('labFrame');source=null;channel='';if(frame){frame.hidden=true;frame.removeAttribute('srcdoc');}var p=document.getElementById('labPaused');if(p){p.hidden=false;p.textContent=run?'Teste pausado. Continue de onde parou ou comece outra rodada.':'Escolha um cenário para começar.';}var b=document.getElementById('labPause');if(b)b.hidden=true;}
function start(){if(!run)return;var f=document.getElementById('labFrame');if(!f)return;var current=run.id;channel=crypto.randomUUID();var nonce=channel;document.getElementById('labPaused').hidden=true;f.hidden=false;document.getElementById('labPause').hidden=false;fetch('primeiro-acesso-teste.html?v=1.0.0',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('Não foi possível abrir o teste.');return r.text();}).then(function(text){if(!run||run.id!==current||channel!==nonce||!f.isConnected)return;source=f.contentWindow;f.srcdoc=text;}).catch(function(e){if(channel!==nonce)return;pause();document.getElementById('labPaused').textContent=e.message+' Tente continuar novamente.';});}
function newRun(){pause();var scenario=document.getElementById('labScenario').value;run={id:crypto.randomUUID(),scenario:scenario,created:new Date().toISOString(),notes:'',rating:'',state:null};db.runs.push(run);db.runs=db.runs.slice(-20);db.current=run.id;persist();details();start();}
function mount(){details();if(resumeOnMount){resumeOnMount=false;start();}document.getElementById('labScenario').onchange=function(){document.getElementById('labGuide').textContent=instructions[this.value];};document.getElementById('labNew').onclick=newRun;document.getElementById('labRestart').onclick=function(){if(!run)return;document.getElementById('labScenario').value=run.scenario;newRun();};document.getElementById('labResume').onclick=start;document.getElementById('labPause').onclick=pause;document.getElementById('labNotes').oninput=function(){if(run){run.notes=this.value;persist();}};document.getElementById('labRating').onchange=function(){if(run){run.rating=this.value;persist();}};document.getElementById('labExport').onclick=function(){var blob=new Blob([JSON.stringify({ambiente:'simulado',versao:'1.0.0',exportado:new Date().toISOString(),rodadas:db.runs},null,2)],{type:'application/json'});var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='easyapp-testes-primeiro-acesso.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);};}
addEventListener('message',function(e){if(!source||e.source!==source||!run||!document.getElementById('labFrame'))return;var m=e.data;if(!m||typeof m!=='object')return;if(m.type==='easyapp:test-ready'){source.postMessage({type:'easyapp:test-init',channel:channel,scenario:run.scenario,data:run.state},'*');return;}if(m.type!=='easyapp:test-state'||m.channel!==channel||!m.data||m.data.schema!==1)return;if(JSON.stringify(m.data).length>100000)return;run.state=m.data;run.updated=new Date().toISOString();persist();history();});
window.TestePrimeiroAcesso={html:html,mount:mount,pause:pause};
})();
